title: GIS Portfolio
description:
remote_theme: pages-themes/minimal

plugins:
  - jekyll-remote-theme

github:
  is_project_page: false

# Load custom CSS
include:
  - assets/css/custom.css

# Navigation
nav:
  - title: "Home"
    url: /GUS5062/
  - title: "About Me"
    url: /GUS5062/about
  - title: "Projects"
    url: /GUS5062/projects
  - title: "Contact"
    url: /GUS5062/contact

color_scheme: light
search_enabled: true
