title: Welcome to my Portfolio for Fundamentals of Geographic Information Systems
description: 
remote_theme: pages-themes/cayman

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: https://sites.google.com/site/shreyaseedas/

# Optional extras
color_scheme: light
logo: /assets/logo.png
search_enabled: true
