title: Fundamentals of GIS, Temple University
description: GIS Portfolio of Shreyasee Das
remote_theme: pages-themes/minimal 

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /https://dasshreyasee.github.io/GUS5062/
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact

# Optional extras
color_scheme: light
search_enabled: true
