title: GIS Portfolio
description: 
remote_theme: pages-themes/minimal 

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme

 
github:
  is_project_page: false 

include:
  - assets/css/custom.css

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact


# Optional extras
color_scheme: light
search_enabled: true
