title: Fundamentals of Geographic Information Systems
description: Portfolio created by Shreyasee Das
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme

github:
  is_project_page: false

# Load custom CSS
include:
  - assets/css/custom.css

defaults:
  - scope:
      path: ""
    values:
      css:
        - assets/css/custom.css

# Navigation links â€” MUST include /GUS5062/
nav:
  - title: "Home"
    url: "/GUS5062/"



color_scheme: light
search_enabled: true
